spring:
  application:
    name: clexp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8080
  
logging:
  level:
    root: INFO
    '[com.clexp]': DEBUG
    '[org.springframework.r2dbc]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web.server]': DEBUG